// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQ3mF1k65rsPvNgLcsZHCRdI1CydS4GI',
    appId: '1:809224944285:web:2d1db56b32fa14718f7274',
    messagingSenderId: '809224944285',
    projectId: 'ncare-5ad1f',
    authDomain: 'ncare-5ad1f.firebaseapp.com',
    storageBucket: 'ncare-5ad1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0fT04mUFhkz2H5Si5C9W8NO6ByhEolP4',
    appId: '1:809224944285:android:450e44587a9096bc8f7274',
    messagingSenderId: '809224944285',
    projectId: 'ncare-5ad1f',
    storageBucket: 'ncare-5ad1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANgBq2eU-kWP3j6yFjyLVPk6_3jcXJ8c0',
    appId: '1:809224944285:ios:be108f6f1c089c8a8f7274',
    messagingSenderId: '809224944285',
    projectId: 'ncare-5ad1f',
    storageBucket: 'ncare-5ad1f.firebasestorage.app',
    iosBundleId: 'com.example.ncare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANgBq2eU-kWP3j6yFjyLVPk6_3jcXJ8c0',
    appId: '1:809224944285:ios:be108f6f1c089c8a8f7274',
    messagingSenderId: '809224944285',
    projectId: 'ncare-5ad1f',
    storageBucket: 'ncare-5ad1f.firebasestorage.app',
    iosBundleId: 'com.example.ncare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQ3mF1k65rsPvNgLcsZHCRdI1CydS4GI',
    appId: '1:809224944285:web:986e97116bc6dac08f7274',
    messagingSenderId: '809224944285',
    projectId: 'ncare-5ad1f',
    authDomain: 'ncare-5ad1f.firebaseapp.com',
    storageBucket: 'ncare-5ad1f.firebasestorage.app',
  );
}
